version: "3"

networks:
  grafana_trial:

volumes:
  app_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana_trial

  loki:
    image: grafana/loki:1.6.1
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana_trial

  promtail:
    image: grafana/promtail:1.6.1
    volumes:
      - app_data:/var/log
    networks:
      - grafana_trial

  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 3001:3000
    networks:
      - grafana_trial

  app:
    build: ./app
    ports:
      - 8081:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana_trial

  db:
    image: grafana/tns-db:latest
    ports:
      - 8082:80
    networks:
      - grafana_trial
